# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the application files
COPY . .

# Specify the command to run the app
CMD ["python", "prod_flask.py"]

# Expose the port the app runs on
EXPOSE 5001