version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - .:/app
  #   depends_on:
  #     - streamlit_app1
  #     - streamlit_app2

  # streamlit_app1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.trackingbot
  #   env_file:
  #     - .env
  #   ports:
  #     - "8241:8241"
  #   volumes:
  #     - .:/app

  # streamlit_app2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.uibot
  #   env_file:
  #     - .env
  #   ports:
  #     - "8245:8245"
  #   volumes:
  #     - .:/app
